CREATE TABLE empresa
(
	ID LONG,
	NOME_FANTASIA VARCHAR(800),
	RAZAO_SOCIAL VARCHAR(800),
	CAMINHO_FOTO VARCHAR(800)
);

CREATE TABLE linha
(
	ID LONG,
    ID_EMPRESA LONG,
	DESCRICAO VARCHAR(800)
);

CREATE TABLE linha_ponto
(
	ID LONG,
    ID_LINHA LONG,
	ID_PONTO LONG
);

CREATE TABLE ponto
(
	ID LONG,
	LATITUDE DECIMAL,
	LONGITUDE DECIMAL,
	NOME VARCHAR(800),
    DESCRICAO VARCHAR(800),
    PARADA BOOLEAN,
    REFERENCIA BOOLEAN,
    CAMINHO_FOTO VARCHAR(800)
);

CREATE TABLE usuario
(
	ID LONG,
	NOME VARCHAR(800),
    EMAIL VARCHAR(800),
    SENHA VARCHAR(800),
    TELEFONE VARCHAR(11)
);


CREATE TABLE historico_do_proco_da_passagem
(
	ID LONG,
	PRECO DOUBLE,
    DATA_DA_ALTERACAO DATE,
    ID_USUARIO LONG
);