-- EXCLUIR A DATABASE SE EXISTIR
--DROP DATABASE   IF     EXISTS AVALIACAO;

-- CRIAR A DATABASE
--CREATE DATABASE IF NOT EXISTS AVALIACAO;

-- CONECTAR A DATABASE
--USE AVALIACAO;

-- CRIAR TABELAS
CREATE TABLE endereco
(
	ID INTEGER AUTO_INCREMENT, PRIMARY KEY (ID),
	RUA VARCHAR(800) NOT NULL,
	NUMERO INTEGER,
	BAIRRO VARCHAR(800) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	COMPLEMENTO VARCHAR(800) NOT NULL,
    ID_CIDADE INTEGER
);

CREATE TABLE empresa
(
	ID INTEGER  AUTO_INCREMENT, PRIMARY KEY (ID),
	NOME_FANTASIA VARCHAR(800) NOT NULL,
	RAZAO_SOCIAL VARCHAR(800) NOT NULL,
	EMAIL VARCHAR(800),
    TELEFONE VARCHAR(15),
	ID_ENDERECO INTEGER
);

CREATE TABLE estado
(
	ID INTEGER  AUTO_INCREMENT, PRIMARY KEY (ID),
	CODIGO_IBGE INTEGER NOT NULL,
	NOME VARCHAR(800) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL
);

CREATE TABLE cidade
(
	ID INTEGER  AUTO_INCREMENT, PRIMARY KEY (ID),
	NOME VARCHAR(800) NOT NULL,
	ID_ESTADO INTEGER NOT NULL
);


CREATE TABLE historico_do_preco_da_passagem
(
	ID INTEGER AUTO_INCREMENT, PRIMARY KEY (ID),
	PRECO DOUBLE NOT NULL,
    DATA_DA_ALTERACAO DATE,
    ID_EMPRESA INTEGER
    
);

ALTER TABLE cidade ADD CONSTRAINT FK_ID_ESTADO_CIDADE FOREIGN KEY (ID_ESTADO) REFERENCES estado (ID);
ALTER TABLE endereco ADD CONSTRAINT FK_ID_CIDADE_ENDERECO FOREIGN KEY (ID_CIDADE) REFERENCES cidade (ID);
ALTER TABLE empresa ADD CONSTRAINT FK_ID_EMPRESA_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES endereco (ID);
ALTER TABLE historico_do_preco_da_passagem ADD CONSTRAINT FK_ID_HISTORICO_DO_PRECO_DA_PASSAGEM_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES empresa (ID);
