CREATE TABLE empresa
(
	ID INTEGER,
	NOME_FANTASIA VARCHAR(800) NOT NULL,
	RAZAO_SOCIAL VARCHAR(800) NOT NULL,
	CAMINHO_FOTO VARCHAR(800)
);

CREATE TABLE historico_do_preco_da_passagem
(
	ID INTEGER,
	PRECO DOUBLE NOT NULL,
    DATA_DA_ALTERACAO DATE,
    ID_USUARIO INTEGER,
    ID_EMPRESA INTEGER
);

CREATE TABLE linha
(
	ID INTEGER,
    ID_EMPRESA INTEGER NOT NULL,
	DESCRICAO VARCHAR(800) NOT NULL
);

CREATE TABLE tipo_ponto
(
	ID INTEGER,
	DESCRICAO VARCHAR(800) NOT NULL
);

CREATE TABLE ponto
(
	ID INTEGER,
	LATITUDE DECIMAL NOT NULL,
	LONGITUDE DECIMAL NOT NULL,
	NOME VARCHAR(800)NOT NULL,
    DESCRICAO VARCHAR(800) NOT NULL,
    ID_TIPO_PONTO INTEGER NOT NULL,
    CAMINHO_FOTO VARCHAR(800)
);

CREATE TABLE linha_ponto
(
	ID INTEGER,
    ID_LINHA INTEGER NOT NULL,
	ID_PONTO INTEGER NOT NULL
);

CREATE TABLE usuario
(
	ID INTEGER,
	NOME VARCHAR(800) NOT NULL,
    EMAIL VARCHAR(800),
    SENHA VARCHAR(800),
    TELEFONE VARCHAR(11)
);


ALTER TABLE empresa ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (ID);
ALTER TABLE historico_do_preco_da_passagem ADD CONSTRAINT PK_HISTORICO_DO_PRECO_DA_PASSAGEM PRIMARY KEY (ID);
ALTER TABLE historico_do_preco_da_passagem ADD CONSTRAINT FK_ID_HISTORICO_DO_PRECO_DA_PASSAGEM_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES empresa (ID);
ALTER TABLE linha ADD CONSTRAINT PK_LINHA PRIMARY KEY (ID);
ALTER TABLE linha ADD CONSTRAINT FK_ID_EMPRESA_LINHA FOREIGN KEY (ID) REFERENCES empresa(ID);
ALTER TABLE tipo_ponto ADD CONSTRAINT PK_TIPO_PONTO PRIMARY KEY (ID);
ALTER TABLE ponto ADD CONSTRAINT PK_PONTO PRIMARY KEY (ID);
ALTER TABLE ponto ADD CONSTRAINT FK_ID_TIPO_PONTO FOREIGN KEY (ID_TIPO_PONTO) REFERENCES tipo_ponto(ID);
ALTER TABLE linha_ponto ADD CONSTRAINT PK_LINHA_PONTO PRIMARY KEY (ID);
ALTER TABLE linha_ponto ADD CONSTRAINT FK_ID_LINHA_LINHA_PONTO FOREIGN KEY (ID_LINHA) REFERENCES linha (ID);
ALTER TABLE linha_ponto ADD CONSTRAINT FK_ID_PONTO_LINHA_PONTO FOREIGN KEY (ID_PONTO) REFERENCES ponto (ID);
ALTER TABLE usuario ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID);



